Issues 159 & 164: UUID as ID and changed alert message for container tht is back and running
agh-docker-monitoring/dockiera-app pull request #170
Opened 2021-11-04 20:34 UTC by jakubsolecki

https://github.com/agh-docker-monitoring/dockiera-app/issues/159 and https://github.com/agh-docker-monitoring/dockiera-app/issues/164

2021-11-04 20:42 UTC, kraleppa commented
Probably because of typescript - should be easy fix (I hope...)

2021-11-04 20:46 UTC, kraleppa commented
@Ilargi12 some fixes on agent side might be needed too

2021-11-04 21:10 UTC, kraleppa requested changes
We need @skupien here

2021-11-04 21:10 UTC, kraleppa commented on frontend/src/redux/hostsSlice.ts
> +//We need @Patryk Skupień here
@skupien could you please check this file... below you are doing some weird stuff with ids assuming that they're integer values and it won't work after change to uuid

2021-11-09 00:38 UTC, skupien commented
Fixed by replacing [] with {}

2021-11-09 00:38 UTC, skupien approved these changes

2021-11-09 14:56 UTC, merged